WebApi/Controllers/ProdutoController.cs
using Aplicacao;
using Aplicacao.Modelos;
using Aplicacao.Utilidades;
using Dominio.Entidades;
using Dominio.Excecoes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Threading.Tasks;

namespace WebApi.Controllers
{
    [Route("api/[controller]")]
    public class ProdutoController : Controller
    {
        [AllowAnonymous]
        [HttpGet]
        public string Iniciar()
        {
            return "A API foi iniciada corretamente.";
        }

        [AllowAnonymous]
        [HttpPost("gerarToken")]
        public IActionResult GerarToken([FromBody]UsuarioModelo usuario, [FromServices]UsuarioAppServico servicoUsuario,
                                        [FromServices]ConfiguracoesAssinatura configuracoesAssinatura,
                                        [FromServices]TokenConfiguracoesModelo tokenConfiguracoes)
        {
            try
            {
                servicoUsuario.LogarUsuario(usuario);

                string token = ProverToken(usuario, tokenConfiguracoes, configuracoesAssinatura);

                return Ok(new { accessToken = token });
            }
            catch (ExpectedException ex)
            {
                return Utilidades.BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return Utilidades.InternalServerError(ex.Message);
            }
        }
            
        [Authorize("Bearer")]
        [HttpPost]        
        [Route("inserirProduto")]
        public IActionResult InserirProduto([FromBody]ProdutoModelo produto, [FromServices]ProdutoAppServico produtoServico)
        {
            try
            {
                int codigoProduto = produtoServico.InserirProduto(produto);

                return Ok(new {
                    Mensagem = "Produto inserido com sucesso.",
                    CodigoProduto = codigoProduto
                });
            }
            catch (ExpectedException ex)
            {
                return Utilidades.BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return Utilidades.InternalServerError(ex.Message);
            }
        }

        [Authorize("Bearer")]
        [HttpPut]
        [Route("editarProduto")]
        public IActionResult EditarProduto([FromServices]ProdutoAppServico produtoServico, [FromBody]ProdutoModelo produto)
        {
            try
            {
                produtoServico.EditarProduto(produto);

                return Ok(new
                {
                    Mensagem = "Produto alterado com sucesso."
                });
            }
            catch (ExpectedException ex)
            {
                return Utilidades.BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return Utilidades.InternalServerError(ex.Message);
            }            
        }

        [Authorize("Bearer")]
        [HttpDelete]
        [Route("excluirProduto/{id}/")]
        public IActionResult ExcluirProduto([FromServices]ProdutoAppServico produtoServico, int id)
        {
            try
            {
                produtoServico.ExcluirProduto(id);

                return Ok(new
                {
                    Mensagem = "Produto excluído com sucesso."
                });
            }
            catch (ExpectedException ex)
            {
                return Utilidades.BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return Utilidades.InternalServerError(ex.Message);
            }
        }

        [Authorize("Bearer")]
        [HttpGet]
        [Route("proverDetalheProduto/{id}/")]
        public IActionResult ProverDetalheProduto([FromServices]ProdutoAppServico produtoServico, int id)
        {
            try
            {
                ProdutoModelo produto = produtoServico.ProverDetalheProduto(id);

                return Ok(produto);
            }
            catch (ExpectedException ex)
            {
                return Utilidades.BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return Utilidades.InternalServerError(ex.Message);
            }
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("proverDetalheTodosProdutos")]
        public async Task<IActionResult> Listar([FromServices]ProdutoAppServico produtoServico, int? numPagina)
        {
            try
            {
                IQueryable<Produto> produtos = produtoServico.ProverDetalheTodosProdutos();

                return View(await Paginacao<Produto>.CreateAsync(produtos.AsNoTracking(), numPagina ?? 1, 10));
            }
            catch (ExpectedException ex)
            {
                return Utilidades.BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return Utilidades.InternalServerError(ex.Message);
            }
        }

        private string ProverToken(UsuarioModelo usuario, TokenConfiguracoesModelo tokenConfiguracoes, ConfiguracoesAssinatura configuracoesAssinatura)
        {
            ClaimsIdentity identity = new ClaimsIdentity(new GenericIdentity(usuario.Id, "Login"));

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString("N")));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.UniqueName, usuario.ChaveAcesso));

            JwtSecurityTokenHandler handler = new JwtSecurityTokenHandler();

            SecurityTokenDescriptor descriptor = new SecurityTokenDescriptor();
            descriptor.Issuer = tokenConfiguracoes.Emissor;
            descriptor.Audience = tokenConfiguracoes.Audiencia;
            descriptor.SigningCredentials = configuracoesAssinatura.SigningCredentials;
            descriptor.Subject = identity;
            descriptor.NotBefore = DateTime.Now;
            descriptor.Expires = descriptor.NotBefore + TimeSpan.FromDays(1);

            SecurityToken securityToken = handler.CreateToken(descriptor);

            return handler.WriteToken(securityToken);            
        }
    }       
}

WebApi/Views/Produto/Listar.cshtml
@model WebApi.Paginacao<Dominio.Entidades.Produto>

@{
    ViewData["Title"] = "Listar";
}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
</head>

<h2 class="text-center" style="margin-top: 20px">Produtos</h2>

<div class="container">
    <div style="float: left; padding-left:15px">
        @if (Model.IndicePagina != 1)
        {
            @Html.ActionLink("Anterior", "Listar", "Produto", new { numPagina = (Model.IndicePagina - 1) })
        }
        else
        {
            <text>Anterior</text>
        }

        @if (Model.IndicePagina != Model.TotalPaginas)
        {
            @Html.ActionLink("Próximo", "Listar", "Produto", new { numPagina = (Model.IndicePagina + 1) })
        }
        else
        {
            <text>Próximo</text>
        }
    </div>

    <div style="float: right; padding-right:15px">
        Página @Model.IndicePagina de @Model.TotalPaginas
    </div>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayName("Id")
                </th>
                <th>
                    @Html.DisplayName("Nome")
                </th>
                <th>
                    @Html.DisplayName("Valor")
                </th>
                <th>
                    @Html.DisplayName("Cor")
                </th>
                <th>
                    @Html.DisplayName("Peso")
                </th>
                <th>
                    @Html.DisplayName("Observação")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Peso)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Observacao)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>